# -*- coding: utf-8 -*-
"""Agile ver 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBCSrVnDDesy2T4V2qUsOy8AzmEkyigp
"""

def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c
temperature_coeffs = [0.02, -0.4, 20]
rainfall_coeffs = [0.006, -0.2, 8]
humidity_coeffs = [0.003, -0.07, 85]
days = [1, 100, 200, 365]
temperature = [quadratic_model(*temperature_coeffs, day) for day in days]
rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
humidity = [quadratic_model(*humidity_coeffs, day) for day in days]
print("Day\tTemperature\tRainfall\tHumidity")
for day, temp, rain, hum in zip(days, temperature, rainfall, humidity):
    print(f"{day}\t{temp:.2f}\t\t{rain:.2f}\t\t{hum:.2f}")