# -*- coding: utf-8 -*-
"""Agile ver 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDs7SHqs76MG-EY7JPegemGRiS0KPFZZ
"""

def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c

with open("/content/Agile data ver 3.txt", "r") as file:
    coefficients = file.readlines()

temperature_coeffs = list(map(float, coefficients[0].strip().split()))
rainfall_coeffs = list(map(float, coefficients[1].strip().split()))
humidity_coeffs = list(map(float, coefficients[2].strip().split()))

days = [1, 100, 200, 365]

temperature = [quadratic_model(*temperature_coeffs, day) for day in days]
rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
humidity = [quadratic_model(*humidity_coeffs, day) for day in days]

print("Day\tTemperature\tRainfall\tHumidity")
for day, temp, rain, hum in zip(days, temperature, rainfall, humidity):
    print(f"{day}\t{temp:.2f}\t\t{rain:.2f}\t\t{hum:.2f}")