# -*- coding: utf-8 -*-
"""Agile ver 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mm3MCKF3vig2MAFBx3yMIyEJjqgZMsYF
"""

import matplotlib.pyplot as plt

def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c

with open("/content/Agile data ver 4.txt", "r") as file:
    coefficient_sets = [list(map(float, line.strip().split())) for line in file]

days = list(range(1, 366))

plt.figure(figsize=(12, 8))
for idx, coeffs in enumerate(coefficient_sets):
    temp_coeffs, rainfall_coeffs, humidity_coeffs = coeffs[:3], coeffs[3:6], coeffs[6:9]
    temperature = [quadratic_model(*temp_coeffs, day) for day in days]
    rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
    humidity = [quadratic_model(*humidity_coeffs, day) for day in days]

    plt.plot(days, temperature, label=f"Temperature (Set {idx + 1})")
    plt.plot(days, rainfall, label=f"Rainfall (Set {idx + 1})")
    plt.plot(days, humidity, label=f"Humidity (Set {idx + 1})")

plt.xlabel("Days")
plt.ylabel("Values")
plt.title("Weather Data for All Sets")
plt.legend()
plt.grid()
plt.show()