# -*- coding: utf-8 -*-
"""Iterative ver 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cj0WDSF4gnO5jL5ZHiIAwv8kmAxZs4rR
"""

import numpy as np
temp_coeffs = [0.02, -0.4, 20]
rainfall_coeffs = [0.006, -0.2, 8]
humidity_coeffs = [0.003, -0.07, 85]
days = [1, 100, 200, 365]
def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c
temperature = [quadratic_model(*temp_coeffs, day) for day in days]
rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
humidity = [quadratic_model(*humidity_coeffs, day) for day in days]
print("Iterative Model - Version 1 (Hardcoded Variables):")
print(f"Days: {days}")
print(f"Temperature: {temperature}")
print(f"Rainfall: {rainfall}")
print(f"Humidity: {humidity}")