# -*- coding: utf-8 -*-
"""Iterative Ver 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7DOQBCYJa5hUNmV4KQQ66VVjwYd1O98
"""

import numpy as np
import matplotlib.pyplot as plt
with open("/content/Iterative data ver 4.txt", "r") as file:
    lines = file.readlines()
temp_coeffs = list(map(float, lines[0].strip().split(',')))
rainfall_coeffs = list(map(float, lines[1].strip().split(',')))
humidity_coeffs = list(map(float, lines[2].strip().split(',')))
additional_coeffs = [list(map(float, line.strip().split(','))) for line in lines[3:]]
days = np.linspace(1, 365, 365)
def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c
temperature = quadratic_model(*temp_coeffs, days)
rainfall = quadratic_model(*rainfall_coeffs, days)
humidity = quadratic_model(*humidity_coeffs, days)
plt.figure(figsize=(12, 6))
plt.plot(days, temperature, label="Temperature (°C)", color="red")
plt.plot(days, rainfall, label="Rainfall (mm)", color="blue")
plt.plot(days, humidity, label="Humidity (%)", color="green")
for idx, coeffs in enumerate(additional_coeffs):
    temp = quadratic_model(*coeffs, days)
    plt.plot(days, temp, label=f"Additional Set {idx + 1}", linestyle="--")
plt.title("Iterative Model - Multiple Sets of Inputs")
plt.xlabel("Day of the Year")
plt.ylabel("Weather Parameters")
plt.legend()
plt.grid()
plt.show()