# -*- coding: utf-8 -*-
"""Waterfall ver 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHjF79PrsNWtDWdcSrdbkpp4TFkiG26b
"""

import matplotlib.pyplot as plt

def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c

def read_multiple_coefficients(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
    coefficients = []
    for line in lines:
        line = line.strip()
        if line and not line.startswith("#"):
            coefficients.append(list(map(float, line.split())))
    return [coefficients[i:i + 3] for i in range(0, len(coefficients), 3)]

filename = "/content/waterfall data ver 4.txt"
coefficients_sets = read_multiple_coefficients(filename)
days = list(range(1, 366))

plt.figure(figsize=(14, 8))
for i, coeffs in enumerate(coefficients_sets):
    temp_coeffs, rainfall_coeffs, humidity_coeffs = coeffs
    temperature = [quadratic_model(*temp_coeffs, day) for day in days]
    rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
    humidity = [quadratic_model(*humidity_coeffs, day) for day in days]
    plt.plot(days, temperature, label=f"Temperature (Set {i + 1})", linestyle='-', color=f"C{i}")
    plt.plot(days, rainfall, label=f"Rainfall (Set {i + 1})", linestyle='--', color=f"C{i}")
    plt.plot(days, humidity, label=f"Humidity (Set {i + 1})", linestyle=':', color=f"C{i}")

plt.title("Waterfall Model - Version 4 ")
plt.xlabel("Days")
plt.ylabel("Values")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()