# -*- coding: utf-8 -*-
"""Waterfall ver 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iuM2JWLiUxqY-kJcjPFY85v1xvWpftAk
"""

def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c
def read_coefficients(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        temp_coeffs = list(map(float, lines[0].strip().split()))
        rainfall_coeffs = list(map(float, lines[1].strip().split()))
        humidity_coeffs = list(map(float, lines[2].strip().split()))
    return temp_coeffs, rainfall_coeffs, humidity_coeffs
filename = "/content/waterfall data ver 3.txt"
temp_coeffs, rainfall_coeffs, humidity_coeffs = read_coefficients(filename)
days = [1, 100, 200, 365]
temperature = [quadratic_model(*temp_coeffs, day) for day in days]
rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
humidity = [quadratic_model(*humidity_coeffs, day) for day in days]
print("\nResults:")
print(f"Days: {days}")
print(f"Temperature: {temperature}")
print(f"Rainfall: {rainfall}")
print(f"Humidity: {humidity}")