# -*- coding: utf-8 -*-
"""Waterfall Ver 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xdDmz6t_Sb6LYaIM592W4t--lT1G9H2
"""

import numpy as np
temp_coeffs = [0.01, -0.3, 25]
rainfall_coeffs = [0.005, -0.1, 5]
humidity_coeffs = [0.002, -0.05, 80]
days = [1, 100, 200, 365]
def quadratic_model(a, b, c, x):
    return a * x**2 + b * x + c
temperature = [quadratic_model(*temp_coeffs, day) for day in days]
rainfall = [quadratic_model(*rainfall_coeffs, day) for day in days]
humidity = [quadratic_model(*humidity_coeffs, day) for day in days]
print("Waterfall Model - Version 1 (Hardcoded Variables):")
print(f"Days: {days}")
print(f"Temperature: {temperature}")
print(f"Rainfall: {rainfall}")
print(f"Humidity: {humidity}")